version: '3.4'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - desafiontt-network
    volumes:
      - postgres-data:/var/lib/postgresql/data

  desafiontt-api:
    image: desafiontt-image
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Default=Host=postgres;Port=5432;Database=postgres;Username=postgres;Password=postgres;
    ports:
      - "5000:80"
    depends_on:
      - postgres
    networks:
      - desafiontt-network

networks:
  desafiontt-network:

volumes:
  postgres-data:
